version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gigpillar_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
